//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionERP.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportViewerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportViewerMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionERP.Web.Resources.ReportViewerMessages", typeof(ReportViewerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click &apos;Refresh&apos; to restore client session..
        /// </summary>
        public static string ReportViewer_ClientExpired {
            get {
                return ResourceManager.GetString("ReportViewer_ClientExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creating report document (Report = &apos;{0}&apos;; Format = &apos;{1}&apos;)..
        /// </summary>
        public static string ReportViewer_ErrorCreatingReportDocument {
            get {
                return ResourceManager.GetString("ReportViewer_ErrorCreatingReportDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sending report document (Report = &apos;{0}&apos;)..
        /// </summary>
        public static string ReportViewer_ErrorSendingDocument {
            get {
                return ResourceManager.GetString("ReportViewer_ErrorSendingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please input a valid value..
        /// </summary>
        public static string ReportViewer_InvalidParameter {
            get {
                return ResourceManager.GetString("ReportViewer_InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Done. Total {0} pages loaded..
        /// </summary>
        public static string ReportViewer_LoadedReportPagesComplete {
            get {
                return ResourceManager.GetString("ReportViewer_LoadedReportPagesComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading report....
        /// </summary>
        public static string ReportViewer_LoadingReport {
            get {
                return ResourceManager.GetString("ReportViewer_LoadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} pages loaded so far....
        /// </summary>
        public static string ReportViewer_LoadingReportPagesInProgress {
            get {
                return ResourceManager.GetString("ReportViewer_LoadingReportPagesInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing or invalid parameter value. Please input valid data for all parameters..
        /// </summary>
        public static string ReportViewer_MissingOrInvalidParameter {
            get {
                return ResourceManager.GetString("ReportViewer_MissingOrInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No page to display..
        /// </summary>
        public static string ReportViewer_NoPageToDisplay {
            get {
                return ResourceManager.GetString("ReportViewer_NoPageToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select all.
        /// </summary>
        public static string ReportViewer_ParameterEditorSelectAll {
            get {
                return ResourceManager.GetString("ReportViewer_ParameterEditorSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clear selection.
        /// </summary>
        public static string ReportViewer_ParameterEditorSelectNone {
            get {
                return ResourceManager.GetString("ReportViewer_ParameterEditorSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        public static string ReportViewer_ParametersAreaPreviewButton {
            get {
                return ResourceManager.GetString("ReportViewer_ParametersAreaPreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparing document to download. Please wait....
        /// </summary>
        public static string ReportViewer_PreparingDownload {
            get {
                return ResourceManager.GetString("ReportViewer_PreparingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparing document to print. Please wait....
        /// </summary>
        public static string ReportViewer_PreparingPrint {
            get {
                return ResourceManager.GetString("ReportViewer_PreparingPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error shown. Throwing promises chain stop error..
        /// </summary>
        public static string ReportViewer_PromisesChainStopError {
            get {
                return ResourceManager.GetString("ReportViewer_PromisesChainStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report processing was canceled..
        /// </summary>
        public static string ReportViewer_RenderingCancelled {
            get {
                return ResourceManager.GetString("ReportViewer_RenderingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find.
        /// </summary>
        public static string ReportViewer_SearchDialogCaptionText {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string ReportViewer_SearchDialogClearTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogClearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match Case.
        /// </summary>
        public static string ReportViewer_SearchDialogMatchCaseTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogMatchCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match Whole Word.
        /// </summary>
        public static string ReportViewer_SearchDialogMatchWholeWordTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogMatchWholeWordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navigate Down.
        /// </summary>
        public static string ReportViewer_SearchDialogNavigateDownTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogNavigateDownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navigate Up.
        /// </summary>
        public static string ReportViewer_SearchDialogNavigateUpTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogNavigateUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No results.
        /// </summary>
        public static string ReportViewer_SearchDialogNoResultsLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogNoResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a page.
        /// </summary>
        public static string ReportViewer_SearchDialogPageText {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Result {0} of {1}.
        /// </summary>
        public static string ReportViewer_SearchDialogResultsFormatLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogResultsFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Showing first {0} results..
        /// </summary>
        public static string ReportViewer_SearchDialogResultsLimitLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogResultsLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a searching....
        /// </summary>
        public static string ReportViewer_SearchDialogSearchInProggress {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogSearchInProggress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search in report contents.
        /// </summary>
        public static string ReportViewer_SearchDialogTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use Regex.
        /// </summary>
        public static string ReportViewer_SearchDialogUseRegexTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SearchDialogUseRegexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string ReportViewer_SendEmailDialogCancelLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CC:.
        /// </summary>
        public static string ReportViewer_SendEmailDialogCCLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogCCLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string ReportViewer_SendEmailDialogClose {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format:.
        /// </summary>
        public static string ReportViewer_SendEmailDialogFormatLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From:.
        /// </summary>
        public static string ReportViewer_SendEmailDialogFromLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string ReportViewer_SendEmailDialogSendLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogSendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject:.
        /// </summary>
        public static string ReportViewer_SendEmailDialogSubjectLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Email.
        /// </summary>
        public static string ReportViewer_SendEmailDialogTitle {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To:.
        /// </summary>
        public static string ReportViewer_SendEmailDialogToLabel {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email format is not valid.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationEmailFormat {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email format is not valid.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationEmailFormat1 {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationEmailFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email field is required.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationEmailRequired {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email field is required.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationEmailRequired1 {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationEmailRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format field is required.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationFormatRequired {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationFormatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format field is required.
        /// </summary>
        public static string ReportViewer_SendEmailDialogValidationFormatRequired1 {
            get {
                return ResourceManager.GetString("ReportViewer_SendEmailDialogValidationFormatRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export.
        /// </summary>
        public static string ReportViewer_ToolbarExportTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Page.
        /// </summary>
        public static string ReportViewer_ToolbarFirstPageTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarFirstPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Page.
        /// </summary>
        public static string ReportViewer_ToolbarLastPageTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarLastPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navigate Backward.
        /// </summary>
        public static string ReportViewer_ToolbarNavigateBackwardTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarNavigateBackwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navigate Forward.
        /// </summary>
        public static string ReportViewer_ToolbarNavigateForwardTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarNavigateForwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next Page.
        /// </summary>
        public static string ReportViewer_ToolbarNextPageTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarNextPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous Page.
        /// </summary>
        public static string ReportViewer_ToolbarPreviousPageTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarPreviousPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print.
        /// </summary>
        public static string ReportViewer_ToolbarPrintTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarPrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        public static string ReportViewer_ToolbarRefreshTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarRefreshTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle Search.
        /// </summary>
        public static string ReportViewer_ToolbarSearchTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send an email.
        /// </summary>
        public static string ReportViewer_ToolbarSendMailTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarSendMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop Rendering.
        /// </summary>
        public static string ReportViewer_ToolbarStopRenderingTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarStopRenderingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle Document Map.
        /// </summary>
        public static string ReportViewer_ToolbarToggleDocumentMapTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarToggleDocumentMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle Parameters Area.
        /// </summary>
        public static string ReportViewer_ToolbarToggleParametersAreaTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarToggleParametersAreaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle Print Preview.
        /// </summary>
        public static string ReportViewer_ToolbarTogglePrintPreviewTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarTogglePrintPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle FullPage/PageWidth.
        /// </summary>
        public static string ReportViewer_ToolbarToggleScaleModeTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarToggleScaleModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom In.
        /// </summary>
        public static string ReportViewer_ToolbarZoomInTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarZoomInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom Out.
        /// </summary>
        public static string ReportViewer_ToolbarZoomOutTitle {
            get {
                return ResourceManager.GetString("ReportViewer_ToolbarZoomOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to get report parameters..
        /// </summary>
        public static string ReportViewer_UnableToGetReportParameters {
            get {
                return ResourceManager.GetString("ReportViewer_UnableToGetReportParameters", resourceCulture);
            }
        }
    }
}
