//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionERP.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TelerikMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelerikMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionERP.Web.Resources.TelerikMessages", typeof(TelerikMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string AutoComplete_Clear {
            get {
                return ResourceManager.GetString("AutoComplete_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No data.
        /// </summary>
        public static string AutoComplete_NoData {
            get {
                return ResourceManager.GetString("AutoComplete_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a decade.
        /// </summary>
        public static string Calendar_Choose_Decade {
            get {
                return ResourceManager.GetString("Calendar_Choose_Decade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a month.
        /// </summary>
        public static string Calendar_Choose_Month {
            get {
                return ResourceManager.GetString("Calendar_Choose_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose an year.
        /// </summary>
        public static string Calendar_Choose_Year {
            get {
                return ResourceManager.GetString("Calendar_Choose_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to the next period.
        /// </summary>
        public static string Calendar_GoToNext {
            get {
                return ResourceManager.GetString("Calendar_GoToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to the previous period.
        /// </summary>
        public static string Calendar_GoToPrevious {
            get {
                return ResourceManager.GetString("Calendar_GoToPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Today.
        /// </summary>
        public static string Calendar_Today {
            get {
                return ResourceManager.GetString("Calendar_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string ComboBox_Clear {
            get {
                return ResourceManager.GetString("ComboBox_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No data.
        /// </summary>
        public static string ComboBox_NoData {
            get {
                return ResourceManager.GetString("ComboBox_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The date format is not parsable. Please enter valid date..
        /// </summary>
        public static string DateInput_ParsingErrorMessage {
            get {
                return ResourceManager.GetString("DateInput_ParsingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The date is not valid..
        /// </summary>
        public static string DateInput_ValidationErrorMessage {
            get {
                return ResourceManager.GetString("DateInput_ValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string DateTimePicker_Cancel {
            get {
                return ResourceManager.GetString("DateTimePicker_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string DateTimePicker_Date {
            get {
                return ResourceManager.GetString("DateTimePicker_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set.
        /// </summary>
        public static string DateTimePicker_Set {
            get {
                return ResourceManager.GetString("DateTimePicker_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time.
        /// </summary>
        public static string DateTimePicker_Time {
            get {
                return ResourceManager.GetString("DateTimePicker_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No data.
        /// </summary>
        public static string DropDownList_NoData {
            get {
                return ResourceManager.GetString("DropDownList_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (All).
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a And.
        /// </summary>
        public static string Filter_And {
            get {
                return ResourceManager.GetString("Filter_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Filter_Cancel {
            get {
                return ResourceManager.GetString("Filter_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string Filter_Clear {
            get {
                return ResourceManager.GetString("Filter_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is equal to.
        /// </summary>
        public static string Filter_DateIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is after.
        /// </summary>
        public static string Filter_DateIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is after or equal to.
        /// </summary>
        public static string Filter_DateIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is before.
        /// </summary>
        public static string Filter_DateIsLessThan {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is before or equal to.
        /// </summary>
        public static string Filter_DateIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is not equal to.
        /// </summary>
        public static string Filter_DateIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is not null.
        /// </summary>
        public static string Filter_DateIsNotNull {
            get {
                return ResourceManager.GetString("Filter_DateIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is null.
        /// </summary>
        public static string Filter_DateIsNull {
            get {
                return ResourceManager.GetString("Filter_DateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is equal to.
        /// </summary>
        public static string Filter_EnumIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is not equal to.
        /// </summary>
        public static string Filter_EnumIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is not null.
        /// </summary>
        public static string Filter_EnumIsNotNull {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is null.
        /// </summary>
        public static string Filter_EnumIsNull {
            get {
                return ResourceManager.GetString("Filter_EnumIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter.
        /// </summary>
        public static string Filter_Filter {
            get {
                return ResourceManager.GetString("Filter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is false.
        /// </summary>
        public static string Filter_IsFalse {
            get {
                return ResourceManager.GetString("Filter_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is true.
        /// </summary>
        public static string Filter_IsTrue {
            get {
                return ResourceManager.GetString("Filter_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is equal to.
        /// </summary>
        public static string Filter_NumberIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is greater than.
        /// </summary>
        public static string Filter_NumberIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is greater than or equal to.
        /// </summary>
        public static string Filter_NumberIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is less than.
        /// </summary>
        public static string Filter_NumberIsLessThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is less than or equal to.
        /// </summary>
        public static string Filter_NumberIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is not equal to.
        /// </summary>
        public static string Filter_NumberIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is not null.
        /// </summary>
        public static string Filter_NumberIsNotNull {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is null.
        /// </summary>
        public static string Filter_NumberIsNull {
            get {
                return ResourceManager.GetString("Filter_NumberIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Or.
        /// </summary>
        public static string Filter_Or {
            get {
                return ResourceManager.GetString("Filter_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contains.
        /// </summary>
        public static string Filter_StringContains {
            get {
                return ResourceManager.GetString("Filter_StringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Does not contain.
        /// </summary>
        public static string Filter_StringDoesNotContain {
            get {
                return ResourceManager.GetString("Filter_StringDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ends with.
        /// </summary>
        public static string Filter_StringEndsWith {
            get {
                return ResourceManager.GetString("Filter_StringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is empty.
        /// </summary>
        public static string Filter_StringIsEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is equal to.
        /// </summary>
        public static string Filter_StringIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is not empty.
        /// </summary>
        public static string Filter_StringIsNotEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is not equal to.
        /// </summary>
        public static string Filter_StringIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is not null.
        /// </summary>
        public static string Filter_StringIsNotNull {
            get {
                return ResourceManager.GetString("Filter_StringIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has value.
        /// </summary>
        public static string Filter_StringIsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is null.
        /// </summary>
        public static string Filter_StringIsNull {
            get {
                return ResourceManager.GetString("Filter_StringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has no value.
        /// </summary>
        public static string Filter_StringIsNullOrEmpty {
            get {
                return ResourceManager.GetString("Filter_StringIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starts with.
        /// </summary>
        public static string Filter_StringStartsWith {
            get {
                return ResourceManager.GetString("Filter_StringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Grid_Cancel {
            get {
                return ResourceManager.GetString("Grid_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Grid_CancelDelete {
            get {
                return ResourceManager.GetString("Grid_CancelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new record.
        /// </summary>
        public static string Grid_Create {
            get {
                return ResourceManager.GetString("Grid_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort Ascending.
        /// </summary>
        public static string Grid_SortAscending {
            get {
                return ResourceManager.GetString("Grid_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort Descending.
        /// </summary>
        public static string Grid_SortDescending {
            get {
                return ResourceManager.GetString("Grid_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        public static string Grid_Update {
            get {
                return ResourceManager.GetString("Grid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drag a column header and drop it here to group by that column.
        /// </summary>
        public static string Group_Empty {
            get {
                return ResourceManager.GetString("Group_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string MultiSelect_Clear {
            get {
                return ResourceManager.GetString("MultiSelect_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No data.
        /// </summary>
        public static string MultiSelect_NoData {
            get {
                return ResourceManager.GetString("MultiSelect_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decrease value.
        /// </summary>
        public static string NumericTextBox_DecreaseValue {
            get {
                return ResourceManager.GetString("NumericTextBox_DecreaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Increase value.
        /// </summary>
        public static string NumericTextBox_IncreaseValue {
            get {
                return ResourceManager.GetString("NumericTextBox_IncreaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} - {1} of {2} items.
        /// </summary>
        public static string Pager_Display {
            get {
                return ResourceManager.GetString("Pager_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No items to display.
        /// </summary>
        public static string Pager_Empty {
            get {
                return ResourceManager.GetString("Pager_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to the first page.
        /// </summary>
        public static string Pager_First {
            get {
                return ResourceManager.GetString("Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a items per page.
        /// </summary>
        public static string Pager_ItemsPerPage {
            get {
                return ResourceManager.GetString("Pager_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to the last page.
        /// </summary>
        public static string Pager_Last {
            get {
                return ResourceManager.GetString("Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More pages.
        /// </summary>
        public static string Pager_MorePages {
            get {
                return ResourceManager.GetString("Pager_MorePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to the next page.
        /// </summary>
        public static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of {0}.
        /// </summary>
        public static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page.
        /// </summary>
        public static string Pager_Page {
            get {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to the previous page.
        /// </summary>
        public static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        public static string Pager_Refresh {
            get {
                return ResourceManager.GetString("Pager_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a all day.
        /// </summary>
        public static string Scheduler_AllDay {
            get {
                return ResourceManager.GetString("Scheduler_AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Scheduler_Cancel {
            get {
                return ResourceManager.GetString("Scheduler_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        public static string Scheduler_Day {
            get {
                return ResourceManager.GetString("Scheduler_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Scheduler_Delete {
            get {
                return ResourceManager.GetString("Scheduler_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Scheduler_Editor_Description {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Event.
        /// </summary>
        public static string Scheduler_Editor_EditorTitle {
            get {
                return ResourceManager.GetString("Scheduler_Editor_EditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End.
        /// </summary>
        public static string Scheduler_Editor_End {
            get {
                return ResourceManager.GetString("Scheduler_Editor_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End time is required..
        /// </summary>
        public static string Scheduler_Editor_EndTimeRequiredValidationMessage {
            get {
                return ResourceManager.GetString("Scheduler_Editor_EndTimeRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End time must be after the Start time..
        /// </summary>
        public static string Scheduler_Editor_EndTimeValueValidationMessage {
            get {
                return ResourceManager.GetString("Scheduler_Editor_EndTimeValueValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Day Event.
        /// </summary>
        public static string Scheduler_Editor_IsAllDay {
            get {
                return ResourceManager.GetString("Scheduler_Editor_IsAllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat.
        /// </summary>
        public static string Scheduler_Editor_Repeat {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string Scheduler_Editor_Start {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start time is required..
        /// </summary>
        public static string Scheduler_Editor_StartTimeRequiredValidationMessage {
            get {
                return ResourceManager.GetString("Scheduler_Editor_StartTimeRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start time must be before End time..
        /// </summary>
        public static string Scheduler_Editor_StartTimeValueValidationMessage {
            get {
                return ResourceManager.GetString("Scheduler_Editor_StartTimeValueValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        public static string Scheduler_Editor_Title {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title is required..
        /// </summary>
        public static string Scheduler_Editor_TitleRequiredValidationMessage {
            get {
                return ResourceManager.GetString("Scheduler_Editor_TitleRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Month.
        /// </summary>
        public static string Scheduler_Month {
            get {
                return ResourceManager.GetString("Scheduler_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MultiDay.
        /// </summary>
        public static string Scheduler_MultiDay {
            get {
                return ResourceManager.GetString("Scheduler_MultiDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        public static string Scheduler_Next {
            get {
                return ResourceManager.GetString("Scheduler_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous.
        /// </summary>
        public static string Scheduler_Previous {
            get {
                return ResourceManager.GetString("Scheduler_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete only this event occurrence or the whole series?.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteRecurring {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete current occurrence.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowOccurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete the series.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowSeries {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Recurring Appointment.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowTitle {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  day(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Daily_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Daily_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat every.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Daily_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Daily_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a After .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_After {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_Label {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Never.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_Never {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  occurrence(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_Occurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_Occurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a On .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_On {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daily.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Daily {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Monthly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Never.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Never {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weekly.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Weekly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yearly.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Yearly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_Day {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a month(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat every.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat on.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a first.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_First {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fourth.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Fourth {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a last.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Last {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a second.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Second {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a third.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Third {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a day.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekdays_Day {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekdays_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weekday.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekdays_Weekday {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekdays_Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weekend day.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekdays_Weekend {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekdays_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a week(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat every.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat on.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a year(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_Interval {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_Of {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat every.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat on.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to edit only this event occurrence or the whole series?.
        /// </summary>
        public static string Scheduler_Recurrence_EditRecurring {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit current occurrence.
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowOccurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit the series.
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowSeries {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Recurring Appointment.
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowTitle {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Scheduler_Save {
            get {
                return ResourceManager.GetString("Scheduler_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show full day.
        /// </summary>
        public static string Scheduler_ShowFullDay {
            get {
                return ResourceManager.GetString("Scheduler_ShowFullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show business hours.
        /// </summary>
        public static string Scheduler_ShowWorkDay {
            get {
                return ResourceManager.GetString("Scheduler_ShowWorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Today.
        /// </summary>
        public static string Scheduler_Today {
            get {
                return ResourceManager.GetString("Scheduler_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Week.
        /// </summary>
        public static string Scheduler_Week {
            get {
                return ResourceManager.GetString("Scheduler_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string TimePicker_Cancel {
            get {
                return ResourceManager.GetString("TimePicker_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        public static string TimePicker_Day {
            get {
                return ResourceManager.GetString("TimePicker_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AM/PM.
        /// </summary>
        public static string TimePicker_DayPeriod {
            get {
                return ResourceManager.GetString("TimePicker_DayPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Era.
        /// </summary>
        public static string TimePicker_Era {
            get {
                return ResourceManager.GetString("TimePicker_Era", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hour.
        /// </summary>
        public static string TimePicker_Hour {
            get {
                return ResourceManager.GetString("TimePicker_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minute.
        /// </summary>
        public static string TimePicker_Minute {
            get {
                return ResourceManager.GetString("TimePicker_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Month.
        /// </summary>
        public static string TimePicker_Month {
            get {
                return ResourceManager.GetString("TimePicker_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Now.
        /// </summary>
        public static string TimePicker_Now {
            get {
                return ResourceManager.GetString("TimePicker_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quarter.
        /// </summary>
        public static string TimePicker_Quarter {
            get {
                return ResourceManager.GetString("TimePicker_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Second.
        /// </summary>
        public static string TimePicker_Second {
            get {
                return ResourceManager.GetString("TimePicker_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set.
        /// </summary>
        public static string TimePicker_Set {
            get {
                return ResourceManager.GetString("TimePicker_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle clock.
        /// </summary>
        public static string TimePicker_ToggleClock {
            get {
                return ResourceManager.GetString("TimePicker_ToggleClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weekday.
        /// </summary>
        public static string TimePicker_WeekDay {
            get {
                return ResourceManager.GetString("TimePicker_WeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year.
        /// </summary>
        public static string TimePicker_Year {
            get {
                return ResourceManager.GetString("TimePicker_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zone.
        /// </summary>
        public static string TimePicker_Zone {
            get {
                return ResourceManager.GetString("TimePicker_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Upload_Cancel {
            get {
                return ResourceManager.GetString("Upload_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string Upload_Clear {
            get {
                return ResourceManager.GetString("Upload_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Done.
        /// </summary>
        public static string Upload_HeaderStatusUploaded {
            get {
                return ResourceManager.GetString("Upload_HeaderStatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uploading....
        /// </summary>
        public static string Upload_HeaderStatusUploading {
            get {
                return ResourceManager.GetString("Upload_HeaderStatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File type not allowed..
        /// </summary>
        public static string Upload_InvalidFileExtension {
            get {
                return ResourceManager.GetString("Upload_InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File size too large..
        /// </summary>
        public static string Upload_InvalidMaxFileSize {
            get {
                return ResourceManager.GetString("Upload_InvalidMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File size too small..
        /// </summary>
        public static string Upload_InvalidMinFileSize {
            get {
                return ResourceManager.GetString("Upload_InvalidMinFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string Upload_Remove {
            get {
                return ResourceManager.GetString("Upload_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retry.
        /// </summary>
        public static string Upload_Retry {
            get {
                return ResourceManager.GetString("Upload_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select files....
        /// </summary>
        public static string Upload_SelectFiles {
            get {
                return ResourceManager.GetString("Upload_SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload.
        /// </summary>
        public static string Upload_UploadFiles {
            get {
                return ResourceManager.GetString("Upload_UploadFiles", resourceCulture);
            }
        }
    }
}
